<?php if(isset($menu) && sizeof($menu) > 0): ?>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu" style="margin-bottom: 5px; display: block; position: static;">  
        <li><a href="<?php echo BASE_URL.Cookie::lenguaje()."/" ?>"><?php echo APP_NAME ?></a></li>
        <?php foreach($menu as $item): ?>
            <?php 
            $_item_style = "";

            if(View::getViewId() && $item["Pag_IdPrincipal"] == View::getViewId())
            {
                $_item_style = "active";
            }

            $dropdown = (isset($item["hijo"]) && sizeof($item["hijo"]) > 0);
            ?>
            <li class="divider"></li>
            <li class="dropdown-submenu <?php echo $_item_style; echo $dropdown ? " dropdown" : "" ?>">
                <a  href="<?php echo $item["Pag_Url"]?>" <?php echo $dropdown ? 'class="dropdown-toggle" data-toggle="dropdown"' : ""; ?>>

                    <?php echo $item["Pag_Nombre"]; echo $dropdown ? ' <b class="caret"></b>' : ""?>
                </a>                                
                <?php if($dropdown): ?>
                    
                        
                            <?php $arbolMenuWidget= new menuWidget();
                                  echo $arbolMenuWidget->arbolMenu('top', $item["hijo"])  
                                    ?>$
                        
                    
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>

<?php endif; ?>